In [ ]:
import numpy as np

arr = np.array([1,2,3])

zeros = np.zeros((2,3))
ones = np.ones((2,3))
eye = np.eye(3)

print(zeros)
print(ones)
print(eye)

rand = np.random.rand(2,3)
randint = np.random.randint(1,10,(3,3))

print(rand)
print(randint)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.9343124  0.92421103 0.80697119]
 [0.54919142 0.4800827  0.27566345]]
[[3 7 2]
 [6 9 8]
 [1 3 1]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print("shape:",arr.shape )
print("Reshaped:",arr.reshape(3,2))
print("DataType:",arr.dtype)
print("Size:",arr.size)
print("Num of Dimensions:",arr.ndim)
print("Maximum:",arr.max())
print("Minimum:",arr.min())
print("Argument Maximum:",arr.argmax())
print("Argument Minimum:",arr.argmin())

shape: (2, 3)
Reshaped: [[1 2]
 [3 4]
 [5 6]]
DataType: int64
Size: 6
Num of Dimensions: 2
Maximum: 6
Minimum: 1
Argument Maximum: 5
Argument Minimum: 0


In [ ]:
copy_arr = arr.copy()
print(copy_arr)
np.append(copy_arr,[10,11])
print(copy_arr)
# np.insert(copy_arr, 1, [100, 200], axis=0)
np.sort(copy_arr, axis=1)
np.delete(copy_arr, 1, axis=0)
np.split(arr, 2)


a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

combined = np.concatenate((a, b), axis=0)

print(combined)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
