In [ ]:
import numpy as np

array = np.array ([[1,2,3],[4,5,6]])

np.save('arr_file.npy', array)
np.savetxt('arr_file.txt', array)

loaded = np.load('arr_file.npy')
loaded_txt = np.loadtxt('arr_file.txt')

print(loaded)
print(loaded_txt)

[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
import random

new_arr = np.random.randint(0,20, size = (5,5))

diagonal = np.diag(new_arr)

all_even = new_arr[new_arr % 2 == 0]

new_arr[new_arr > 10] = 0


print(new_arr)
print("\n",diagonal)
print("\n",all_even)


[[10  2  4  5  2]
 [ 0  9  0  0 10]
 [ 1  3  2  0  0]
 [ 8  0  0  0  5]
 [ 9  0  0  4  0]]

 [10  9  2  0  0]

 [10  2  4  2 18 14 10  2 18  8  0  0 14  4]


In [ ]:
a = np.random.rand(3,1)
b = np.random.rand(1,4)

result = a+b
print(a)
print("\n",b)
print("\n",result)

[[0.73991445]
 [0.7611164 ]
 [0.1604481 ]]

 [[0.99144847 0.72250784 0.23736677 0.9491364 ]]

 [[1.73136293 1.46242229 0.97728123 1.68905085]
 [1.75256488 1.48362424 0.99848318 1.7102528 ]
 [1.15189657 0.88295594 0.39781487 1.1095845 ]]


In [ ]:
int_arr = np.random.randint(1,20,size=(2,2))
print(int_arr.dtype)

int_arr.astype(np.float32)



int64


array([[4., 7.],
       [2., 5.]], dtype=float32)

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(a)
print(b)

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[    1    64]
 [ 2187 65536]]


In [ ]:
arr = np.array([1, 4, 9])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.max(arr))
print(np.abs(arr))

[1. 2. 3.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03]
[ 0.84147098 -0.7568025   0.41211849]
9
[1 4 9]
